### ISSUE TITLE
Linda-client in Windows only has one active connection and does not stake

### ISSUE THREAD

**Issue by mr-snipes** [Lindacoin/Linda#16]
My client has only one active connection. 

Most of the time lindacoin wallet shows that i have one conenction to the network only. My conf-file has configured 2 IPs.

addnode=185.82.200.183 addnode=185.183.98.138

So i added af few nodes i found in a similar thread:

addnode 67.60.255.115 add addnode 38.70.200.12 add addnode 27.145.42.7 add addnode 211.2.80.127 add

The wallet still claims that it only has one connection overall. 
It also states that i should stake in 3 days - it keeps stating that for two weeks now.

**Comment by Typhoonx53** [comment]
https://www.coinexchange.io/network/peers/LINDA
This is the latest list with all the active nodes, please add them all (110+) to the Linda.conf file and your 1st problem is solved
As for staking: All depends on the network weight and a bit of luck. The more coins you have the faster you will stake your coins. If you have only a few 100000 coins the chance of hitting a payout is lower BUT the payout amount will be exactly the same since your coins that have not staked gain 'age'... So in your case (im pretty sure you staked by now) you will get a payout for 21 days staking.  
Happy staking!

**Comment by mr-snipes** [comment]
Thx, i copied the addnode-lines from the left hand side to my conf-file. 
The situation is unchanged: i have sometimes one connection, very briefly 2 and then again 0 connections.
The debug-log is filled with stuff like this: 

IRC got new address: 145.239.86.4:33820
IRC got who
IRC got who
IRC got new address: 45.55.212.165:33820
IRC got who
IRC got new address: 104.238.159.161:33820
IRC got join
IRC got new address: 96.241.146.140:33820


and 

IRC got new address: 182.253.163.50:28284
socket recv error 10054
socket recv error 10053
socket recv error 10054
IRC got join
IRC got new address: 171.100.200.44:28284
IRC got join
IRC got join
IRC got join

**Comment by nisanb** [comment]
Will be fixed in the released version #25 

Please close the ticket.

**Comment by parsa12345** [comment]
how i can send ticket to linda support team????
