### ISSUE TITLE
SYNCING PROBLEMS!!

### ISSUE THREAD

**Issue by randy446** [Lindacoin/Linda#60]
Ok I am calling it! Shit coin! Everybody on here is having syncing problems since version 2. 
WHAT THE HELL!  NO!!! I dont want to bootstrap I want to go through the pain and load the wallet and have it sync but NOOOO I got to bootstrap. Ok ok I will bootstrap...Then I find out there is NO BOOTSTRAP FILE! or it would be on HERE instead of me searching high and low on the internet!!! You know your suppose to have a read me file. You know your suppose to have code THAT WORKS. You know that your suppose to have a bootstrap file on here or go through the pain of the LONG SYNC. You know that when a person with windows installs then uninstalls RIGHT!! Its like I am having a problem with my computer....What do I do... shut it down then bring it back up. I downloaded Navcoin the other day. It has finished SYNCING IN ONE NIGHT WITHOUT A BOOTSTRAP. Why do you think that is? Navcoin has been here LONGER than Lindacoin.... With Lindacoin I need a BOOTSTRAP?!?

I just wanted you to know... YOU SUCK AT BEING CODERS!!

**Comment by SanShiner** [comment]
Yoy clearly don't have any understading what is issue tracker. Reading this kind of text just proves that biggest issue is the writer.

**Comment by Chris-Lindacoin** [comment]
Hey Randy, tough day buddy?  Its all good I hear your frustration.  The issue with it not syncing from scratch is due to us having a hard fork at the end of March.  You can see in the pull requests this has been fixed for the next wallet release.  If you need the link for the dynamic bootstrap its at lindaprojectinfo.com/bootstrapping  The current team took this project over only a few months ago and are repairing stuff at a rapid rate, hang in there and you will see this isnt a shit coin.  If I can ever help you reach out at chris@lindacoin.com

**Comment by BraapAround** [comment]
Close this issue. It's BS.

**Comment by randy446** [comment]
Oops I got it to finally work.. thanks Chris
